name: Nightly

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - uses: ncipollo/release-action@v1
        with:
          tag: nightly
          name: Nightly
          commit: ${{ github.sha }}
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          makeLatest: false
          artifacts: artifacts/*
